name: Deploy to Firebase Hosting on push

on:
  push:
    branches:
      - master # Asegúrate de cambiar esto si usas otra rama como tu rama principal

jobs:
  deploy:
    runs-on: windows-latest # O cambia a windows-latest si prefieres Windows

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # Asegúrate de usar la versión de Node.js que corresponda a tu proyecto

    - name: Install Dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Deploy to Firebase Hosting
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
